sc_map_builder:
  ros__parameters:
    cloud_topic: /rkbot/lio/cloud_world
    odom_topic: /rkbot/lio/odom
    output_dir: /home/lgl/Documents/trae_projects/autoinitialpose/AutoInitialize/scancontext_db
    map_frame: rkbot/world
    save_every_n: 3
    sync_queue_size: 20
    num_rings: 20
    num_sectors: 60
    max_radius: 80.0
    lidar_height: 0.0
