btc_map_builder:
  ros__parameters:
    cloud_topic: /rkbot/lio/cloud_world
    odom_topic: /rkbot/lio/odom
    output_dir: /home/lgl/Documents/trae_projects/autoinitialpose/AutoInitialize/btc_db
    map_frame: rkbot/world
    save_every_n: 3
    sync_queue_size: 20
    is_high_fly: 0
    parallel_stl_enable: 1
    parallel_stl_min_size: 256
